kind: ConfigMap
apiVersion: v1
metadata:
  name: selinux-policies
data:
  ping_rule.te: |
    module ping_rule 1.0;

    require {
      type install_t;
      type setfiles_mac_t;
      class process2 { nnp_transition nosuid_transition };
    } 

    #============= install_t ==============
    allow install_t setfiles_mac_t:process2 { nnp_transition nosuid_transition };

---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: semodule-loader
  labels:
    app: semodule-loader
spec:
  selector:
    matchLabels:
      app: semodule-loader
  template:
    metadata:
      labels:
        app: semodule-loader
    spec:
      hostNetwork: true
      nodeSelector:
        node-role.kubernetes.io/worker: ""
      containers:
      - name: semodule-loader
        image: quay.io/ykashtan/semodule-loader:latest
        command: ['sh', '-c', '/scripts/chroot.sh /scripts/semodule-load.sh && echo "Installing selinux policies" && sleep infinity']
        securityContext:
          privileged: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: FallbackToLogsOnError
        env:
          - name: POLICY_NAME
            value: ping_rule.te
        volumeMounts:
        - mountPath: /selinux-policies
          name: selinux-policies
        - mountPath: /host
          name: host
      hostNetwork: true
      restartPolicy: Always
      terminationGracePeriodSeconds: 10
      volumes:
      - configMap:
          name: selinux-policies
        name: selinux-policies
      - hostPath:
          path: /
          type: Directory
        name: host
