apiVersion: v1
kind: Pod
metadata:
   name: restricted-suid
spec:
   containers:
   - name: bomb
     image: quay.io/ykashtan/restricted-suid:latest
     command: ["/bin/bash"]
     args: ["-c","whoamis"]
